### ISSUE TITLE
Dapper Query ToHtmlTable with tableAttributes show "Object reference not set to an instance of an object"

### ISSUE THREAD

**Issue by shps951023** [shps951023/HtmlTableHelper#35]
![image](https://user-images.githubusercontent.com/12729184/136754473-6dd7b197-5d55-4bae-aa8e-445f2ea52012.png)

![image](https://user-images.githubusercontent.com/12729184/136754638-6863fe85-1e59-4a24-95b8-a424a280aec3.png)

**Comment by au5ton** [comment]
I encountered this Exception and for me it appeared to be because on Line 84 in the snippet below `this._HtmlTableHelperBuilder.Caption` is null. I will try to submit a pull request.

https://github.com/shps951023/HtmlTableHelper/blob/745e02b0be079d6ddb4dd0e4df4d4b29c7bdba2c/Src/ITWeiHan.HtmlTableHelper/HtmlTableGenerater.cs#L79C14-L95
